version: "3.0"

services:
  db:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=phpframework
    ports:
      - 33061:3306
  app:
    image: phpframework/stable:1.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
    links:
      - db
    depends_on:
      - db
    tty: true